### ISSUE TITLE
Book of Mormon Title Page

### ISSUE THREAD

**Issue by zxcv654** [awerkamp/markdown-scriptures-standard-works-church-of-jesus-christ#1]
Is the Title page missing?  Great job on this, by the way.  I've just decided to keep my notes in Obsidian rather than the Gospel Library and this is just what I needed!

**Comment by awerkamp** [comment]
That’s great, good luck. Yes, it could very well be missing. You may have to add it in manually. Some neat things I’ve learned about Obsidian recently are you can use an exclamation mark in front of a reference to display a reference inline ![[]] and you can link out to other file types in your vault such a videos, photos, or pdfs. Benjamin AwerkampOn Dec 18, 2022, at 7:54 AM, zxcv654 ***@***.***> wrote:﻿
Is the Title page missing?  Great job on this, by the way.  I've just decided to keep my notes in Obsidian rather than the Gospel Library and this is just what I needed!
